version: "3.8"
services:
  server:
    image: server
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ${SERVER_HOST}
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  nginx:
    image: reverse-proxy
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${NGINX_HOST}
    env_file: .env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}

  


# version: '3'

# services:

#   node:
#     image: brenotorquato/node-fullcycle
#     container_name: node
#     networks:
#       - nodenet

#   nginx:
#     image: brenotorquato/nginx-fullcycle-v2
#     container_name: nginx
#     networks:
#       - nodenet
#     ports:
#       - "8080:80"

# networks:
#   nodenet:
#     driver: bridge
