version: "3.8"

networks:
  nodenet:
    driver: bridge

services:
  node:
    image: server
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: ${SERVER_HOST}
    env_file: .env
    networks:
      - nodenet

  nginx:
    image: reverse-proxy
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: ${NGINX_HOST}
    env_file: .env
    networks:
      - nodenet
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
