version: "3.8"

networks:
  nodenet:
    driver: bridge

services:
  node:
    image: brenotorquato/node_docker_desafio2
    container_name: ${SERVER_HOST}
    env_file: .env
    build:
      context: ./node
      dockerfile: Dockerfile
    networks:
      - nodenet

  nginx:
    image: brenotorquato/nginx_docker_desafio2
    container_name: ${NGINX_HOST}
    restart: always
    env_file: .env
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - nodenet
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: ${MYSQL_HOST}
    restart: always
    env_file: .env
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - nodenet