version: "3.8"

networks:
  nodenet:
    driver: bridge

services:
  node:
    image: brenotorquato/node_docker_desafio2
    container_name: ${SERVER_HOST}
    env_file: .env
    build:
      context: ./node
      dockerfile: Dockerfile
    networks:
      - nodenet

  nginx:
    image: brenotorquato/nginx_docker_desafio2
    container_name: ${NGINX_HOST}
    restart: always
    env_file: .env
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - nodenet
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
