version: '3.8'

networks:
  node-network:
    driver: bridge

services:
  database:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: ${MYSQL_HOST}
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - node-network

  app:
    build:
      context: ./node
    container_name: ${SERVER_HOST}
    entrypoint: dockerize -wait tcp://${MYSQL_HOST}:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - database

  nginx:
    container_name: ${NGINX_HOST}
    restart: always
    env_file: .env
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - node-network
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}